<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4020.12">
  <POU Name="Delay" Id="{9b91272d-9848-4c41-8af9-1af6a2bdd545}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Delay
VAR_INPUT
	Delay_On	: BOOL;
	Delay_Time	: TIME;
END_VAR
VAR_OUTPUT
	Delay_Done	: BOOL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="Delay">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>